name: Frontend Backend Pipeline

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # FRONTEND
      - name: Install Frontend Dependencies
        working-directory: frontend/train
        run: npm ci

      - name: Build Frontend
        working-directory: frontend/train
        run: npm run build

      # BACKEND
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Run Backend Tests
        working-directory: backend
        run: npm test